ALTER TABLE macroregiones ADD COLUMN activo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE ejes_tematicos ADD COLUMN activo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE instituciones ADD COLUMN activo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE territorios ADD COLUMN activo BOOLEAN NOT NULL DEFAULT TRUE;
