UPDATE proyectos
SET estado = CASE estado
    WHEN 'PENDIENTE' THEN 'ACTIVO'
    WHEN 'EN_CURSO' THEN 'ACTIVO'
    WHEN 'FINALIZADO' THEN 'CERRADO'
    ELSE estado
END;

ALTER TABLE proyectos ALTER COLUMN estado SET DEFAULT 'ACTIVO';
